SET FOREIGN_KEY_CHECKS=0;
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (101, 'Standard Room Non AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (102, 'Standard Room Non AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (103, 'Standard Room Non AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (104, 'Standard Room Non AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (105, 'Standard Room Non AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (106, 'Standard Room Non AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (107, 'Standard Room Non AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (108, 'Standard Room Non AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (201, 'Standard AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (202, 'Standard AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (203, 'Standard AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (204, 'Standard AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (205, 'Standard AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (206, 'Standard AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (207, 'Standard AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (208, 'Standard AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (301, 'Deluxe AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (302, 'Deluxe AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (303, 'Deluxe AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (304, 'Deluxe AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (305, 'Deluxe AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (306, 'Deluxe AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (307, 'Deluxe AC', 0);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (308, 'Deluxe AC', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (401, 'Lakeview Deluxe Fam', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (402, 'Lakeview Deluxe Fam', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (403, 'Lakeview Deluxe Fam', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (404, 'Lakeview Deluxe Fam', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (501, 'Suite', 1);
INSERT INTO dbs_project.room (Room_No, Room_Type, Availability) VALUES (502, 'Suite', 0);